#!/bin/zsh
# AUTHOR = Artesia 2016

feh --bg-scale ~/.wallpaper.jpg &

ws1=  # Terminal
ws2=  # Chromium/Firefox
ws3=  # Discord
ws4=  # Telegram
ws5=  # Coding
ws6=  # Gaming
ws7=  # Video
ws8=  # Miscelanous/File Manager
ws9=  # My notes/documents. 
ws10= # Settings 
ws11= # Keepass

bspc config border_width        0
bspc config window_gap          0 
bspc config focus_follows_pointer true

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

#
# bspc monitor -d i ii iii iv v vi vii viii ix x
#
##dual monitor bois for left
bspc monitor HDMI1 -d $ws1 $ws2 $ws3 $ws4 $ws5 
bspc monitor eDP1 -d $ws6 $ws7 $ws8 $ws9 $ws10 $ws11
#
##dual monitor bois for right
#bspc monitor eDP1 -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6
#bspc monitor HDMI1 -d $ws7 $ws8 $ws9 $ws10 $ws11
#
##single monitor(laptop)
#bspc monitor eDP1 -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9 $ws10 $ws11

#
# Rules for organisation
#

bspc rule -a Termite desktop=^1
bspc rule -a URxvt state=floating
bspc rule -a Firefox desktop=^2
bspc rule -a discord-canary desktop=^3
bspc rule -a telegram-desktop desktop=^4
bspc rule -a subl desktop=^5
bspc rule -a steam-native desktop=^6
bspc rule -a mpv desktop=^7
bspc rule -a Thunar desktop=^8
bspc rule -a wikidpad desktop=^9
bspc rule -a lxappearance desktop=^10
bspc rule -a keepass desktop=^11

sh ~/.config/polybar/run_polybar.sh
sh ~/.config/bspwm/autostart &
